max_clauses(100).
enable_recursion.
head_pred(DerivationallyRelatedForm,2).
body_pred(InstanceHypernym,2).
body_pred(Hypernym,2).
body_pred(AlsoSee,2).
body_pred(MemberMeronym,2).
body_pred(SynsetDomainTopicOf,2).
body_pred(HasPart,2).
body_pred(MemberOfDomainUsage,2).
body_pred(MemberOfDomainRegion,2).
body_pred(VerbGroup,2).
body_pred(SimilarTo,2).
