max_clauses(10).
enable_recursion.
head_pred(derivationallyRelatedForm,2).
body_pred(instanceHypernym,2).
body_pred(hypernym,2).
body_pred(alsoSee,2).
body_pred(memberMeronym,2).
body_pred(synsetDomainTopicOf,2).
body_pred(hasPart,2).
body_pred(memberOfDomainUsage,2).
body_pred(memberOfDomainRegion,2).
body_pred(verbGroup,2).
body_pred(similarTo,2).
