father(christopher, arthur).
father(christopher, victoria).
father(andrew, james).
father(andrew, jennifer).
father(james, colin).
father(james, charlotte).
father(roberto, emilio).
father(roberto, lucia).
father(pierro, marco).
father(pierro, angela).
father(marco, alfonso).
father(marco, sophia).
mother(penelope, arthur).
mother(penelope, victoria).
mother(christine, james).
mother(christine, jennifer).
mother(victoria, colin).
mother(victoria, charlotte).
mother(maria, emilio).
mother(maria, lucia).
mother(francesca, marco).
mother(francesca, angela).
mother(lucia, alfonso).
mother(lucia, sophia).
husband(christopher, penelope).
husband(andrew, christine).
husband(arthur, margaret).
husband(james, victoria).
husband(charles, jennifer).
husband(roberto, maria).
husband(pierro, francesca).
husband(emilio, gina).
husband(marco, lucia).
husband(tomaso, angela).
wife(penelope, christopher).
wife(christine, andrew).
wife(margaret, arthur).
wife(victoria, james).
wife(jennifer, charles).
wife(maria, roberto).
wife(francesca, pierro).
wife(gina, emilio).
wife(lucia, marco).
wife(angela, tomaso).
son(arthur, christopher).
son(arthur, penelope).
son(james, andrew).
son(james, christine).
son(colin, victoria).
son(colin, james).
son(emilio, roberto).
son(emilio, maria).
son(marco, pierro).
son(marco, francesca).
son(alfonso, lucia).
son(alfonso, marco).
daughter(victoria, christopher).
daughter(victoria, penelope).
daughter(jennifer, andrew).
daughter(jennifer, christine).
daughter(charlotte, victoria).
daughter(charlotte, james).
daughter(lucia, roberto).
daughter(lucia, maria).
daughter(angela, pierro).
daughter(angela, francesca).
daughter(sophia, lucia).
daughter(sophia, marco).
brother(arthur, victoria).
brother(james, jennifer).
brother(colin, charlotte).
brother(emilio, lucia).
brother(marco, angela).
brother(alfonso, sophia).
sister(victoria, arthur).
sister(jennifer, james).
sister(charlotte, colin).
sister(lucia, emilio).
sister(angela, marco).
sister(sophia, alfonso).
uncle(arthur, colin).
uncle(charles, colin).
uncle(arthur, charlotte).
uncle(charles, charlotte).
uncle(emilio, alfonso).
uncle(tomaso, alfonso).
uncle(emilio, sophia).
uncle(tomaso, sophia).
aunt(jennifer, colin).
aunt(margaret, colin).
aunt(jennifer, charlotte).
aunt(margaret, charlotte).
aunt(angela, alfonso).
aunt(gina, alfonso).
aunt(angela, sophia).
aunt(gina, sophia).
nephew(colin, arthur).
nephew(colin, jennifer).
nephew(alfonso, emilio).
nephew(alfonso, angela).
nephew(colin, margaret).
nephew(colin, charles).
nephew(alfonso, gina).
nephew(alfonso, tomaso).
niece(charlotte, arthur).
niece(charlotte, jennifer).
niece(sophia, emilio).
niece(sophia, angela).
niece(charlotte, margaret).
niece(charlotte, charles).
niece(sophia, gina).
niece(sophia, tomaso).
