pos(father(christopher, arthur)).
pos(father(christopher, victoria)).
pos(father(andrew, james)).
pos(father(andrew, jennifer)).
pos(father(james, colin)).
pos(father(james, charlotte)).
pos(father(roberto, emilio)).
pos(father(roberto, lucia)).
pos(father(pierro, marco)).
pos(father(pierro, angela)).
pos(father(marco, alfonso)).
pos(father(marco, sophia)).
pos(mother(penelope, arthur)).
pos(mother(penelope, victoria)).
pos(mother(christine, james)).
pos(mother(christine, jennifer)).
pos(mother(victoria, colin)).
pos(mother(victoria, charlotte)).
pos(mother(maria, emilio)).
pos(mother(maria, lucia)).
pos(mother(francesca, marco)).
pos(mother(francesca, angela)).
pos(mother(lucia, alfonso)).
pos(mother(lucia, sophia)).
pos(husband(christopher, penelope)).
pos(husband(andrew, christine)).
pos(husband(arthur, margaret)).
pos(husband(james, victoria)).
pos(husband(charles, jennifer)).
pos(husband(roberto, maria)).
pos(husband(pierro, francesca)).
pos(husband(emilio, gina)).
pos(husband(marco, lucia)).
pos(husband(tomaso, angela)).
pos(wife(penelope, christopher)).
pos(wife(christine, andrew)).
pos(wife(margaret, arthur)).
pos(wife(victoria, james)).
pos(wife(jennifer, charles)).
pos(wife(maria, roberto)).
pos(wife(francesca, pierro)).
pos(wife(gina, emilio)).
pos(wife(lucia, marco)).
pos(wife(angela, tomaso)).
pos(son(arthur, christopher)).
pos(son(arthur, penelope)).
pos(son(james, andrew)).
pos(son(james, christine)).
pos(son(colin, victoria)).
pos(son(colin, james)).
pos(son(emilio, roberto)).
pos(son(emilio, maria)).
pos(son(marco, pierro)).
pos(son(marco, francesca)).
pos(son(alfonso, lucia)).
pos(son(alfonso, marco)).
pos(daughter(victoria, christopher)).
pos(daughter(victoria, penelope)).
pos(daughter(jennifer, andrew)).
pos(daughter(jennifer, christine)).
pos(daughter(charlotte, victoria)).
pos(daughter(charlotte, james)).
pos(daughter(lucia, roberto)).
pos(daughter(lucia, maria)).
pos(daughter(angela, pierro)).
pos(daughter(angela, francesca)).
pos(daughter(sophia, lucia)).
pos(daughter(sophia, marco)).
pos(brother(arthur, victoria)).
pos(brother(james, jennifer)).
pos(brother(colin, charlotte)).
pos(brother(emilio, lucia)).
pos(brother(marco, angela)).
pos(brother(alfonso, sophia)).
pos(sister(victoria, arthur)).
pos(sister(jennifer, james)).
pos(sister(charlotte, colin)).
pos(sister(lucia, emilio)).
pos(sister(angela, marco)).
pos(sister(sophia, alfonso)).
pos(uncle(arthur, colin)).
pos(uncle(charles, colin)).
pos(uncle(arthur, charlotte)).
pos(uncle(charles, charlotte)).
pos(uncle(emilio, alfonso)).
pos(uncle(tomaso, alfonso)).
pos(uncle(emilio, sophia)).
pos(uncle(tomaso, sophia)).
pos(aunt(jennifer, colin)).
pos(aunt(margaret, colin)).
pos(aunt(jennifer, charlotte)).
pos(aunt(margaret, charlotte)).
pos(aunt(angela, alfonso)).
pos(aunt(gina, alfonso)).
pos(aunt(angela, sophia)).
pos(aunt(gina, sophia)).
pos(nephew(colin, arthur)).
pos(nephew(colin, jennifer)).
pos(nephew(alfonso, emilio)).
pos(nephew(alfonso, angela)).
pos(nephew(colin, margaret)).
pos(nephew(colin, charles)).
pos(nephew(alfonso, gina)).
pos(nephew(alfonso, tomaso)).
pos(niece(charlotte, arthur)).
pos(niece(charlotte, jennifer)).
pos(niece(sophia, emilio)).
pos(niece(sophia, angela)).
pos(niece(charlotte, margaret)).
pos(niece(charlotte, charles)).
pos(niece(sophia, gina)).
pos(niece(sophia, tomaso)).
